import { Locales } from "intlayer";
import type { IntlayerConfig } from "intlayer";

/**
 * Intlayer configuration file documentation
 * @see https://intlayer.org/doc/concept/configuration
 */

const config: IntlayerConfig = {
  ai: {
    apiKey: process.env.OPENAI_API_KEY,
    /**
     * Additional context for the translations
     *
     * Can be use in addition of the dictionary `description` field
     */
    applicationContext: [
      "termcn is an open source registry of terminal UI components for Ink and OpenTUI, distributed with the shadcn CLI.",
      "Keep product nouns untranslated: termcn, shadcn, Ink, OpenTUI, React, npm, pnpm, CLI, MCP, registry item names and code identifiers.",
      "Tone is concise and developer facing, matching shadcn/ui documentation copy.",
    ].join("\n"),
    model: "gpt-5-mini",
    /**
     * AI provider to use.
     * Options: 'openai', 'anthropic', 'mistral', 'deepseek', 'gemini', 'ollama', 'openrouter', 'alibaba', 'fireworks', 'groq', 'huggingface', 'bedrock', 'googlevertex', 'togetherai', 'lmstudio', 'moonshotai'
     */
    provider: "openai",
  },
  build: {
    /**
     * Indicates if the build should check TypeScript types
     */
    checkTypes: false,

    /**
     * (Experimental feature)
     *
     * Minify the dictionaries to reduce the bundle size.
     */
    minify: false,

    /**
     * (Experimental feature)
     *
     * Purge the unused keys in a dictionaries
     */
    purge: false,
  },
  compiler: {
    enabled: false,

    /**
     * Defines the output files path for autogenerated content (compiler / autofill / extract)
     *
     * - `./` paths are resolved relative to the component directory.
     * - `/` paths are resolved relative to the project root (`baseDir`).
     */
    output: ({ fileName }) => `./${fileName}.content.ts`,

    /**
     * Indicates if the components should be saved after being transformed.
     */
    saveComponents: false,
  },
  dictionary: {
    /**
     * Controls how dictionaries are imported.
     * - "static": Statically imported at build time.
     * - "dynamic": Dynamically imported using Suspense.
     * - "fetch": Fetched dynamically via the live sync API.
     */
    importMode: "static",
  },
  editor: {
    /**
     * URL of your application for origin validation.
     */
    applicationURL: "http://localhost:3000",

    /**
     * Whether the visual editor is enabled.
     */
    enabled: false,
  },
  internationalization: {
    /**
     * Default locale used as a fallback if the requested locale is not found.
     */
    defaultLocale: Locales.ENGLISH,
    locales: [
      Locales.ENGLISH,
      Locales.CHINESE_SIMPLIFIED_CHINA,
      Locales.JAPANESE,
      Locales.KOREAN,
      Locales.SPANISH,
      Locales.FRENCH,
      Locales.PORTUGUESE,
    ],
  },
  routing: {
    /**
     * Enables the Intlayer locale-routing proxy (middleware).
     * Handles locale detection, redirects and rewrites in dev, preview and SSR.
     */
    enableProxy: true,

    /**
     * Locale routing strategy.
     * - "prefix-no-default": Prefix all except the default locale (e.g., /docs, /fr/docs).
     */
    mode: "prefix-no-default",
  },
};

export default config;
