import type { Theme } from "@/components/ui/opentui-theme-provider";

export const lucentOrngTheme: Theme = {
  border: {
    color: "#808080",
    focusColor: "#ec5b2b",
    style: "rounded",
  },
  colors: {
    accent: "#fff7f1",
    accentForeground: "#2a1a15",
    background: "#2a1a15",
    border: "#808080",
    error: "#e06c75",
    errorForeground: "#2a1a15",
    focusRing: "#ec5b2b",
    foreground: "#eeeeee",
    info: "#56b6c2",
    infoForeground: "#2a1a15",
    muted: "#1a100d",
    mutedForeground: "#808080",
    primary: "#ec5b2b",
    primaryForeground: "#2a1a15",
    secondary: "#3d2521",
    secondaryForeground: "#eeeeee",
    selection: "#ec5b2b",
    selectionForeground: "#2a1a15",
    success: "#6ba1e6",
    successForeground: "#2a1a15",
    warning: "#ec5b2b",
    warningForeground: "#2a1a15",
  },
  name: "lucent-orng",
  spacing: {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    6: 6,
    8: 8,
  },
  typography: {
    base: "",
    bold: true,
    lg: "bold",
    sm: "dim",
    xl: "bold",
  },
};
