import type { Theme } from "@/components/ui/opentui-theme-provider";

export const orngTheme: Theme = {
  border: {
    color: "#808080",
    focusColor: "#ec5b2b",
    style: "rounded",
  },
  colors: {
    accent: "#fff7f1",
    accentForeground: "#0a0a0a",
    background: "#0a0a0a",
    border: "#808080",
    error: "#e06c75",
    errorForeground: "#0a0a0a",
    focusRing: "#ec5b2b",
    foreground: "#eeeeee",
    info: "#56b6c2",
    infoForeground: "#0a0a0a",
    muted: "#050505",
    mutedForeground: "#808080",
    primary: "#ec5b2b",
    primaryForeground: "#0a0a0a",
    secondary: "#151515",
    secondaryForeground: "#eeeeee",
    selection: "#ec5b2b",
    selectionForeground: "#0a0a0a",
    success: "#6ba1e6",
    successForeground: "#0a0a0a",
    warning: "#ec5b2b",
    warningForeground: "#0a0a0a",
  },
  name: "orng",
  spacing: {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    6: 6,
    8: 8,
  },
  typography: {
    base: "",
    bold: true,
    lg: "bold",
    sm: "dim",
    xl: "bold",
  },
};
