/* eslint-disable typescript-eslint/ban-ts-comment, typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-examples.mts
// Do not edit this file directly.
import * as React from "react";

export const ExamplesIndex: Record<string, Record<string, any>> = {
  ink: {
    "alert-custom": {
      component: React.lazy(async () => {
        const mod = await import("./ink/alert-custom");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "alert-custom";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/alert-custom.tsx",
      name: "alert-custom",
    },
    "alert-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/alert-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "alert-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/alert-demo.tsx",
      name: "alert-demo",
    },
    "alert-error": {
      component: React.lazy(async () => {
        const mod = await import("./ink/alert-error");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "alert-error";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/alert-error.tsx",
      name: "alert-error",
    },
    "alert-no-border": {
      component: React.lazy(async () => {
        const mod = await import("./ink/alert-no-border");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "alert-no-border";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/alert-no-border.tsx",
      name: "alert-no-border",
    },
    "alert-warning": {
      component: React.lazy(async () => {
        const mod = await import("./ink/alert-warning");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "alert-warning";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/alert-warning.tsx",
      name: "alert-warning",
    },
    "app-shell-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/app-shell-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "app-shell-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/app-shell-demo.tsx",
      name: "app-shell-demo",
    },
    "aspect-ratio-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/aspect-ratio-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "aspect-ratio-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/aspect-ratio-demo.tsx",
      name: "aspect-ratio-demo",
    },
    "badge-basic": {
      component: React.lazy(async () => {
        const mod = await import("./ink/badge-basic");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "badge-basic";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/badge-basic.tsx",
      name: "badge-basic",
    },
    "badge-bold": {
      component: React.lazy(async () => {
        const mod = await import("./ink/badge-bold");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "badge-bold";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/badge-bold.tsx",
      name: "badge-bold",
    },
    "badge-custom-border": {
      component: React.lazy(async () => {
        const mod = await import("./ink/badge-custom-border");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "badge-custom-border";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/badge-custom-border.tsx",
      name: "badge-custom-border",
    },
    "badge-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/badge-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "badge-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/badge-demo.tsx",
      name: "badge-demo",
    },
    "banner-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/banner-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "banner-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/banner-demo.tsx",
      name: "banner-demo",
    },
    "banner-error": {
      component: React.lazy(async () => {
        const mod = await import("./ink/banner-error");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "banner-error";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/banner-error.tsx",
      name: "banner-error",
    },
    "banner-success": {
      component: React.lazy(async () => {
        const mod = await import("./ink/banner-success");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "banner-success";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/banner-success.tsx",
      name: "banner-success",
    },
    "bar-chart-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/bar-chart-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "bar-chart-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/bar-chart-demo.tsx",
      name: "bar-chart-demo",
    },
    "big-text-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/big-text-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "big-text-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/big-text-demo.tsx",
      name: "big-text-demo",
    },
    "big-text-fonts": {
      component: React.lazy(async () => {
        const mod = await import("./ink/big-text-fonts");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "big-text-fonts";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/big-text-fonts.tsx",
      name: "big-text-fonts",
    },
    "box-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/box-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "box-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/box-demo.tsx",
      name: "box-demo",
    },
    "breadcrumb-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/breadcrumb-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "breadcrumb-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/breadcrumb-demo.tsx",
      name: "breadcrumb-demo",
    },
    "bullet-list-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/bullet-list-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "bullet-list-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/bullet-list-demo.tsx",
      name: "bullet-list-demo",
    },
    "card-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/card-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "card-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/card-demo.tsx",
      name: "card-demo",
    },
    "center-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/center-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "center-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/center-demo.tsx",
      name: "center-demo",
    },
    "chat-message-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/chat-message-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "chat-message-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/chat-message-demo.tsx",
      name: "chat-message-demo",
    },
    "chat-thread-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/chat-thread-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "chat-thread-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/chat-thread-demo.tsx",
      name: "chat-thread-demo",
    },
    "checkbox-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/checkbox-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "checkbox-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/checkbox-demo.tsx",
      name: "checkbox-demo",
    },
    "checkbox-group-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/checkbox-group-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "checkbox-group-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/checkbox-group-demo.tsx",
      name: "checkbox-group-demo",
    },
    "clipboard-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/clipboard-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "clipboard-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/clipboard-demo.tsx",
      name: "clipboard-demo",
    },
    "clock-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/clock-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "clock-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/clock-demo.tsx",
      name: "clock-demo",
    },
    "code-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/code-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "code-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/code-demo.tsx",
      name: "code-demo",
    },
    "code-multiline": {
      component: React.lazy(async () => {
        const mod = await import("./ink/code-multiline");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "code-multiline";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/code-multiline.tsx",
      name: "code-multiline",
    },
    "color-picker-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/color-picker-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "color-picker-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/color-picker-demo.tsx",
      name: "color-picker-demo",
    },
    "columns-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/columns-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "columns-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/columns-demo.tsx",
      name: "columns-demo",
    },
    "command-palette-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/command-palette-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "command-palette-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/command-palette-demo.tsx",
      name: "command-palette-demo",
    },
    "confirm-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/confirm-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "confirm-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/confirm-demo.tsx",
      name: "confirm-demo",
    },
    "conversation-history-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/conversation-history-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "conversation-history-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/conversation-history-demo.tsx",
      name: "conversation-history-demo",
    },
    "data-grid-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/data-grid-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "data-grid-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/data-grid-demo.tsx",
      name: "data-grid-demo",
    },
    "date-picker-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/date-picker-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "date-picker-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/date-picker-demo.tsx",
      name: "date-picker-demo",
    },
    "definition-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/definition-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "definition-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/definition-demo.tsx",
      name: "definition-demo",
    },
    "dialog-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/dialog-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "dialog-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/dialog-demo.tsx",
      name: "dialog-demo",
    },
    "diff-view-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/diff-view-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "diff-view-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/diff-view-demo.tsx",
      name: "diff-view-demo",
    },
    "digits-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/digits-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "digits-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/digits-demo.tsx",
      name: "digits-demo",
    },
    "directory-tree-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/directory-tree-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "directory-tree-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/directory-tree-demo.tsx",
      name: "directory-tree-demo",
    },
    "divider-custom": {
      component: React.lazy(async () => {
        const mod = await import("./ink/divider-custom");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "divider-custom";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/divider-custom.tsx",
      name: "divider-custom",
    },
    "divider-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/divider-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "divider-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/divider-demo.tsx",
      name: "divider-demo",
    },
    "drawer-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/drawer-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "drawer-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/drawer-demo.tsx",
      name: "drawer-demo",
    },
    "email-input-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/email-input-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "email-input-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/email-input-demo.tsx",
      name: "email-input-demo",
    },
    "embedded-terminal-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/embedded-terminal-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "embedded-terminal-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/embedded-terminal-demo.tsx",
      name: "embedded-terminal-demo",
    },
    "error-boundary-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/error-boundary-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "error-boundary-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/error-boundary-demo.tsx",
      name: "error-boundary-demo",
    },
    "error-retry-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/error-retry-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "error-retry-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/error-retry-demo.tsx",
      name: "error-retry-demo",
    },
    "file-change-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/file-change-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "file-change-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/file-change-demo.tsx",
      name: "file-change-demo",
    },
    "file-picker-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/file-picker-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "file-picker-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/file-picker-demo.tsx",
      name: "file-picker-demo",
    },
    "form-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/form-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "form-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/form-demo.tsx",
      name: "form-demo",
    },
    "form-field-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/form-field-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "form-field-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/form-field-demo.tsx",
      name: "form-field-demo",
    },
    "gauge-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/gauge-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "gauge-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/gauge-demo.tsx",
      name: "gauge-demo",
    },
    "git-status-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/git-status-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "git-status-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/git-status-demo.tsx",
      name: "git-status-demo",
    },
    "gradient-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/gradient-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "gradient-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/gradient-demo.tsx",
      name: "gradient-demo",
    },
    "gradient-presets": {
      component: React.lazy(async () => {
        const mod = await import("./ink/gradient-presets");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "gradient-presets";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/gradient-presets.tsx",
      name: "gradient-presets",
    },
    "grid-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/grid-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "grid-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/grid-demo.tsx",
      name: "grid-demo",
    },
    "heading-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/heading-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "heading-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/heading-demo.tsx",
      name: "heading-demo",
    },
    "heat-map-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/heat-map-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "heat-map-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/heat-map-demo.tsx",
      name: "heat-map-demo",
    },
    "help-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/help-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "help-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/help-demo.tsx",
      name: "help-demo",
    },
    "help-screen-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/help-screen-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "help-screen-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/help-screen-demo.tsx",
      name: "help-screen-demo",
    },
    "image-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/image-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "image-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/image-demo.tsx",
      name: "image-demo",
    },
    "info-box-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/info-box-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "info-box-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/info-box-demo.tsx",
      name: "info-box-demo",
    },
    "json-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/json-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "json-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/json-demo.tsx",
      name: "json-demo",
    },
    "key-value-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/key-value-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "key-value-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/key-value-demo.tsx",
      name: "key-value-demo",
    },
    "keyboard-shortcuts-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/keyboard-shortcuts-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "keyboard-shortcuts-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/keyboard-shortcuts-demo.tsx",
      name: "keyboard-shortcuts-demo",
    },
    "line-chart-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/line-chart-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "line-chart-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/line-chart-demo.tsx",
      name: "line-chart-demo",
    },
    "link-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/link-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "link-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/link-demo.tsx",
      name: "link-demo",
    },
    "link-show-href": {
      component: React.lazy(async () => {
        const mod = await import("./ink/link-show-href");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "link-show-href";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/link-show-href.tsx",
      name: "link-show-href",
    },
    "list-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/list-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "list-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/list-demo.tsx",
      name: "list-demo",
    },
    "log-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/log-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "log-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/log-demo.tsx",
      name: "log-demo",
    },
    "login-flow-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/login-flow-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "login-flow-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/login-flow-demo.tsx",
      name: "login-flow-demo",
    },
    "markdown-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/markdown-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "markdown-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/markdown-demo.tsx",
      name: "markdown-demo",
    },
    "markdown-streaming-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/markdown-streaming-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "markdown-streaming-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/markdown-streaming-demo.tsx",
      name: "markdown-streaming-demo",
    },
    "masked-input-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/masked-input-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "masked-input-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/masked-input-demo.tsx",
      name: "masked-input-demo",
    },
    "menu-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/menu-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "menu-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/menu-demo.tsx",
      name: "menu-demo",
    },
    "modal-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/modal-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "modal-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/modal-demo.tsx",
      name: "modal-demo",
    },
    "model-selector-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/model-selector-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "model-selector-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/model-selector-demo.tsx",
      name: "model-selector-demo",
    },
    "multi-progress-compact": {
      component: React.lazy(async () => {
        const mod = await import("./ink/multi-progress-compact");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "multi-progress-compact";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/multi-progress-compact.tsx",
      name: "multi-progress-compact",
    },
    "multi-progress-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/multi-progress-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "multi-progress-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/multi-progress-demo.tsx",
      name: "multi-progress-demo",
    },
    "multi-select-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/multi-select-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "multi-select-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/multi-select-demo.tsx",
      name: "multi-select-demo",
    },
    "notification-center-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/notification-center-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "notification-center-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/notification-center-demo.tsx",
      name: "notification-center-demo",
    },
    "number-input-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/number-input-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "number-input-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/number-input-demo.tsx",
      name: "number-input-demo",
    },
    "pagination-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/pagination-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "pagination-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/pagination-demo.tsx",
      name: "pagination-demo",
    },
    "panel-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/panel-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "panel-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/panel-demo.tsx",
      name: "panel-demo",
    },
    "password-input-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/password-input-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "password-input-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/password-input-demo.tsx",
      name: "password-input-demo",
    },
    "path-input-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/path-input-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "path-input-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/path-input-demo.tsx",
      name: "path-input-demo",
    },
    "pie-chart-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/pie-chart-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "pie-chart-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/pie-chart-demo.tsx",
      name: "pie-chart-demo",
    },
    "popover-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/popover-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "popover-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/popover-demo.tsx",
      name: "popover-demo",
    },
    "progress-bar-custom": {
      component: React.lazy(async () => {
        const mod = await import("./ink/progress-bar-custom");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "progress-bar-custom";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/progress-bar-custom.tsx",
      name: "progress-bar-custom",
    },
    "progress-bar-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/progress-bar-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "progress-bar-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/progress-bar-demo.tsx",
      name: "progress-bar-demo",
    },
    "progress-circle-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/progress-circle-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "progress-circle-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/progress-circle-demo.tsx",
      name: "progress-circle-demo",
    },
    "progress-circle-sizes": {
      component: React.lazy(async () => {
        const mod = await import("./ink/progress-circle-sizes");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "progress-circle-sizes";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/progress-circle-sizes.tsx",
      name: "progress-circle-sizes",
    },
    "qr-code-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/qr-code-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "qr-code-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/qr-code-demo.tsx",
      name: "qr-code-demo",
    },
    "radio-group-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/radio-group-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "radio-group-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/radio-group-demo.tsx",
      name: "radio-group-demo",
    },
    "scroll-view-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/scroll-view-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "scroll-view-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/scroll-view-demo.tsx",
      name: "scroll-view-demo",
    },
    "scroll-view-scrollbar": {
      component: React.lazy(async () => {
        const mod = await import("./ink/scroll-view-scrollbar");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "scroll-view-scrollbar";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/scroll-view-scrollbar.tsx",
      name: "scroll-view-scrollbar",
    },
    "search-input-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/search-input-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "search-input-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/search-input-demo.tsx",
      name: "search-input-demo",
    },
    "select-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/select-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "select-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/select-demo.tsx",
      name: "select-demo",
    },
    "setup-flow-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/setup-flow-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "setup-flow-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/setup-flow-demo.tsx",
      name: "setup-flow-demo",
    },
    "sidebar-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/sidebar-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "sidebar-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/sidebar-demo.tsx",
      name: "sidebar-demo",
    },
    "skeleton-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/skeleton-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "skeleton-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/skeleton-demo.tsx",
      name: "skeleton-demo",
    },
    "skeleton-static": {
      component: React.lazy(async () => {
        const mod = await import("./ink/skeleton-static");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "skeleton-static";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/skeleton-static.tsx",
      name: "skeleton-static",
    },
    "spacer-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/spacer-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "spacer-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/spacer-demo.tsx",
      name: "spacer-demo",
    },
    "sparkline-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/sparkline-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "sparkline-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/sparkline-demo.tsx",
      name: "sparkline-demo",
    },
    "spinner-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/spinner-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "spinner-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/spinner-demo.tsx",
      name: "spinner-demo",
    },
    "spinner-styles": {
      component: React.lazy(async () => {
        const mod = await import("./ink/spinner-styles");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "spinner-styles";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/spinner-styles.tsx",
      name: "spinner-styles",
    },
    "splash-screen-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/splash-screen-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "splash-screen-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/splash-screen-demo.tsx",
      name: "splash-screen-demo",
    },
    "stack-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/stack-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "stack-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/stack-demo.tsx",
      name: "stack-demo",
    },
    "status-message-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/status-message-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "status-message-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/status-message-demo.tsx",
      name: "status-message-demo",
    },
    "status-message-variants": {
      component: React.lazy(async () => {
        const mod = await import("./ink/status-message-variants");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "status-message-variants";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/status-message-variants.tsx",
      name: "status-message-variants",
    },
    "stopwatch-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/stopwatch-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "stopwatch-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/stopwatch-demo.tsx",
      name: "stopwatch-demo",
    },
    "streaming-text-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/streaming-text-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "streaming-text-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/streaming-text-demo.tsx",
      name: "streaming-text-demo",
    },
    "tabbed-content-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/tabbed-content-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "tabbed-content-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/tabbed-content-demo.tsx",
      name: "tabbed-content-demo",
    },
    "table-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/table-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "table-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/table-demo.tsx",
      name: "table-demo",
    },
    "table-selectable": {
      component: React.lazy(async () => {
        const mod = await import("./ink/table-selectable");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "table-selectable";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/table-selectable.tsx",
      name: "table-selectable",
    },
    "table-sortable": {
      component: React.lazy(async () => {
        const mod = await import("./ink/table-sortable");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "table-sortable";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/table-sortable.tsx",
      name: "table-sortable",
    },
    "tabs-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/tabs-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "tabs-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/tabs-demo.tsx",
      name: "tabs-demo",
    },
    "tag-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/tag-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "tag-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/tag-demo.tsx",
      name: "tag-demo",
    },
    "tag-input-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/tag-input-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "tag-input-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/tag-input-demo.tsx",
      name: "tag-input-demo",
    },
    "text-area-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/text-area-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "text-area-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/text-area-demo.tsx",
      name: "text-area-demo",
    },
    "text-input-cursor": {
      component: React.lazy(async () => {
        const mod = await import("./ink/text-input-cursor");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "text-input-cursor";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/text-input-cursor.tsx",
      name: "text-input-cursor",
    },
    "text-input-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/text-input-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "text-input-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/text-input-demo.tsx",
      name: "text-input-demo",
    },
    "text-input-label": {
      component: React.lazy(async () => {
        const mod = await import("./ink/text-input-label");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "text-input-label";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/text-input-label.tsx",
      name: "text-input-label",
    },
    "text-input-placeholder": {
      component: React.lazy(async () => {
        const mod = await import("./ink/text-input-placeholder");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "text-input-placeholder";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/text-input-placeholder.tsx",
      name: "text-input-placeholder",
    },
    "theme-showcase": {
      component: React.lazy(async () => {
        const mod = await import("./ink/theme-showcase");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "theme-showcase";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/theme-showcase.tsx",
      name: "theme-showcase",
    },
    "thinking-block-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/thinking-block-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "thinking-block-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/thinking-block-demo.tsx",
      name: "thinking-block-demo",
    },
    "time-picker-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/time-picker-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "time-picker-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/time-picker-demo.tsx",
      name: "time-picker-demo",
    },
    "timer-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/timer-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "timer-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/timer-demo.tsx",
      name: "timer-demo",
    },
    "toast-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/toast-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "toast-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/toast-demo.tsx",
      name: "toast-demo",
    },
    "toast-error": {
      component: React.lazy(async () => {
        const mod = await import("./ink/toast-error");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "toast-error";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/toast-error.tsx",
      name: "toast-error",
    },
    "toggle-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/toggle-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "toggle-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/toggle-demo.tsx",
      name: "toggle-demo",
    },
    "token-usage-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/token-usage-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "token-usage-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/token-usage-demo.tsx",
      name: "token-usage-demo",
    },
    "tool-approval-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/tool-approval-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "tool-approval-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/tool-approval-demo.tsx",
      name: "tool-approval-demo",
    },
    "tool-call-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/tool-call-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "tool-call-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/tool-call-demo.tsx",
      name: "tool-call-demo",
    },
    "tooltip-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/tooltip-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "tooltip-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/tooltip-demo.tsx",
      name: "tooltip-demo",
    },
    "tree-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/tree-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "tree-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/tree-demo.tsx",
      name: "tree-demo",
    },
    "tree-select-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/tree-select-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "tree-select-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/tree-select-demo.tsx",
      name: "tree-select-demo",
    },
    "usage-monitor-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/usage-monitor-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "usage-monitor-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/usage-monitor-demo.tsx",
      name: "usage-monitor-demo",
    },
    "virtual-list-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/virtual-list-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "virtual-list-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/virtual-list-demo.tsx",
      name: "virtual-list-demo",
    },
    "welcome-screen-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/welcome-screen-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "welcome-screen-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/welcome-screen-demo.tsx",
      name: "welcome-screen-demo",
    },
    "wizard-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/wizard-demo");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "wizard-demo";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/ink/wizard-demo.tsx",
      name: "wizard-demo",
    },
  },
};
