import type { Theme } from "@/registry/bases/opentui/ui/types";

export const auraTheme: Theme = {
  border: {
    color: "#6d6a7e",
    focusColor: "#a277ff",
    style: "rounded",
  },
  colors: {
    accent: "#ff6767",
    accentForeground: "#15141b",
    background: "#15141b",
    border: "#6d6a7e",
    error: "#ff6767",
    errorForeground: "#15141b",
    focusRing: "#a277ff",
    foreground: "#edecee",
    info: "#82e2ff",
    infoForeground: "#15141b",
    muted: "#242329",
    mutedForeground: "#6d6a7e",
    primary: "#a277ff",
    primaryForeground: "#15141b",
    secondary: "#2a2834",
    secondaryForeground: "#edecee",
    selection: "#a277ff",
    selectionForeground: "#15141b",
    success: "#61ffca",
    successForeground: "#15141b",
    warning: "#ffca85",
    warningForeground: "#15141b",
  },
  name: "aura",
  spacing: {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    6: 6,
    8: 8,
  },
  typography: {
    base: "",
    bold: true,
    lg: "bold",
    sm: "dim",
    xl: "bold",
  },
};
