import type { Theme } from "@/registry/bases/ink/ui/types";

export const opencodeTheme: Theme = {
  border: {
    color: "#808080",
    focusColor: "#9d7cd8",
    style: "round",
  },
  colors: {
    accent: "#9d7cd8",
    accentForeground: "#0a0a0a",
    background: "#0a0a0a",
    border: "#808080",
    error: "#e06c75",
    errorForeground: "#0a0a0a",
    focusRing: "#9d7cd8",
    foreground: "#eeeeee",
    info: "#56b6c2",
    infoForeground: "#0a0a0a",
    muted: "#050505",
    mutedForeground: "#808080",
    primary: "#fab283",
    primaryForeground: "#0a0a0a",
    secondary: "#151515",
    secondaryForeground: "#eeeeee",
    selection: "#fab283",
    selectionForeground: "#0a0a0a",
    success: "#7fd88f",
    successForeground: "#0a0a0a",
    warning: "#f5a742",
    warningForeground: "#0a0a0a",
  },
  name: "opencode",
  spacing: {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    6: 6,
    8: 8,
  },
  typography: {
    base: "",
    bold: true,
    lg: "bold",
    sm: "dim",
    xl: "bold",
  },
};
