import type { Theme } from "@/registry/bases/ink/ui/types";

export const zenburnTheme: Theme = {
  border: {
    color: "#9f9f9f",
    focusColor: "#f0dfaf",
    style: "round",
  },
  colors: {
    accent: "#93e0e3",
    accentForeground: "#3f3f3f",
    background: "#3f3f3f",
    border: "#9f9f9f",
    error: "#cc9393",
    errorForeground: "#3f3f3f",
    focusRing: "#f0dfaf",
    foreground: "#dcdccc",
    info: "#dfaf8f",
    infoForeground: "#3f3f3f",
    muted: "#2f2f2f",
    mutedForeground: "#9f9f9f",
    primary: "#8cd0d3",
    primaryForeground: "#3f3f3f",
    secondary: "#4f4f4f",
    secondaryForeground: "#dcdccc",
    selection: "#8cd0d3",
    selectionForeground: "#3f3f3f",
    success: "#7f9f7f",
    successForeground: "#3f3f3f",
    warning: "#f0dfaf",
    warningForeground: "#3f3f3f",
  },
  name: "zenburn",
  spacing: {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    6: 6,
    8: 8,
  },
  typography: {
    base: "",
    bold: true,
    lg: "bold",
    sm: "dim",
    xl: "bold",
  },
};
