import { t } from "intlayer";
import type { Dictionary } from "intlayer";

const docsSidebarContent = {
  content: {
    basic: t({
      en: "Basic",
      es: "Básicos",
      fr: "Base",
      ja: "基本",
      ko: "기본",
      pt: "Básicos",
      "zh-CN": "基础",
    }),
    changelog: t({
      en: "Changelog",
      es: "Registro de cambios",
      fr: "Journal des modifications",
      ja: "変更履歴",
      ko: "변경 이력",
      pt: "Registro de alterações",
      "zh-CN": "更新日志",
    }),
    charts: t({
      en: "Charts",
      es: "Gráficos",
      fr: "Graphiques",
      ja: "チャート",
      ko: "차트",
      pt: "Gráficos",
      "zh-CN": "图表",
    }),
    components: t({
      en: "Components",
      es: "Componentes",
      fr: "Composants",
      ja: "コンポーネント",
      ko: "컴포넌트",
      pt: "Componentes",
      "zh-CN": "组件",
    }),
    dither: t({
      en: "Dither",
      es: "Tramado",
      fr: "Tramage",
      ja: "ディザ",
      ko: "디더",
      pt: "Pontilhado",
      "zh-CN": "抖动",
    }),
    installation: t({
      en: "Installation",
      es: "Instalación",
      fr: "Installation",
      ja: "インストール",
      ko: "설치",
      pt: "Instalação",
      "zh-CN": "安装",
    }),
    introduction: t({
      en: "Introduction",
      es: "Introducción",
      fr: "Introduction",
      ja: "はじめに",
      ko: "소개",
      pt: "Introdução",
      "zh-CN": "简介",
    }),
    llmsTxt: t({
      en: "llms.txt",
      es: "llms.txt",
      fr: "llms.txt",
      ja: "llms.txt",
      ko: "llms.txt",
      pt: "llms.txt",
      "zh-CN": "llms.txt",
    }),
    mcp: t({
      en: "MCP",
      es: "MCP",
      fr: "MCP",
      ja: "MCP",
      ko: "MCP",
      pt: "MCP",
      "zh-CN": "MCP",
    }),
    new: t({
      en: "New",
      es: "Nuevo",
      fr: "Nouveau",
      ja: "新規",
      ko: "새로운",
      pt: "Novo",
      "zh-CN": "新",
    }),
    registry: t({
      en: "Registry",
      es: "Registro",
      fr: "Registre",
      ja: "レジストリ",
      ko: "레지스트리",
      pt: "Registro",
      "zh-CN": "注册表",
    }),
    sections: t({
      en: "Sections",
      es: "Secciones",
      fr: "Sections",
      ja: "セクション",
      ko: "섹션",
      pt: "Seções",
      "zh-CN": "章节",
    }),
    templates: t({
      en: "Templates",
      es: "Plantillas",
      fr: "Modèles",
      ja: "テンプレート",
      ko: "템플릿",
      pt: "Modelos",
      "zh-CN": "模板",
    }),
    themes: t({
      en: "Themes",
      es: "Temas",
      fr: "Thèmes",
      ja: "テーマ",
      ko: "테마",
      pt: "Temas",
      "zh-CN": "主题",
    }),
    theming: t({
      en: "Theming",
      es: "Personalización de temas",
      fr: "Personnalisation des thèmes",
      ja: "テーマ設定",
      ko: "테마 설정",
      pt: "Personalização de temas",
      "zh-CN": "主题定制",
    }),
  },
  key: "docs-sidebar",
} satisfies Dictionary;

export default docsSidebarContent;
