import { enu, insert, t } from "intlayer";
import type { Dictionary } from "intlayer";

const launchWeekContent = {
  content: {
    changelog: t({
      en: "Changelog",
      es: "Registro de cambios",
      fr: "Journal des modifications",
      ja: "変更履歴",
      ko: "변경 이력",
      pt: "Registro de alterações",
      "zh-CN": "更新日志",
    }),
    countdownAriaLabel: insert(
      t({
        en: "{{days}} days, {{hours}} hours, {{minutes}} minutes, {{seconds}} seconds until the next launch",
        es: "{{days}} días, {{hours}} horas, {{minutes}} minutos, {{seconds}} segundos hasta el próximo lanzamiento",
        fr: "{{days}} jours, {{hours}} heures, {{minutes}} minutes, {{seconds}} secondes avant le prochain lancement",
        ja: "次のローンチまで {{days}} 日 {{hours}} 時間 {{minutes}} 分 {{seconds}} 秒",
        ko: "다음 출시까지 {{days}}일 {{hours}}시간 {{minutes}}분 {{seconds}}초",
        pt: "{{days}} dias, {{hours}} horas, {{minutes}} minutos, {{seconds}} segundos até o próximo lançamento",
        "zh-CN": "距离下次发布还有 {{days}} 天 {{hours}} 小时 {{minutes}} 分 {{seconds}} 秒",
      })
    ),
    countdownLoadingAriaLabel: t({
      en: "Loading the launch countdown",
      es: "Cargando la cuenta regresiva del lanzamiento",
      fr: "Chargement du compte à rebours du lancement",
      ja: "ローンチのカウントダウンを読み込み中",
      ko: "출시 카운트다운을 불러오는 중",
      pt: "Carregando a contagem regressiva do lançamento",
      "zh-CN": "正在加载发布倒计时",
    }),
    heroTagline: t({
      en: "Five days. Five releases.",
      es: "Cinco días. Cinco lanzamientos.",
      fr: "Cinq jours. Cinq versions.",
      ja: "5 日間、5 つのリリース。",
      ko: "5일. 5번의 릴리스.",
      pt: "Cinco dias. Cinco lançamentos.",
      "zh-CN": "五天，五次发布。",
    }),
    nextLaunch: insert(
      t({
        en: "Next launch: {{day}}",
        es: "Próximo lanzamiento: {{day}}",
        fr: "Prochain lancement : {{day}}",
        ja: "次のローンチ: {{day}}",
        ko: "다음 출시: {{day}}",
        pt: "Próximo lançamento: {{day}}",
        "zh-CN": "下次发布：{{day}}",
      })
    ),
    noReleaseYet: t({
      en: "No release yet",
      es: "Aún no hay lanzamiento",
      fr: "Pas encore de version",
      ja: "まだリリースはありません",
      ko: "아직 릴리스 없음",
      pt: "Ainda sem lançamento",
      "zh-CN": "尚无发布",
    }),
    noReleaseYetDescription: t({
      en: "Updates will appear here when something ships.",
      es: "Las novedades aparecerán aquí cuando se publique algo.",
      fr: "Les nouveautés apparaîtront ici dès qu'une version sera publiée.",
      ja: "何かが公開されると、ここに更新が表示されます。",
      ko: "무언가 출시되면 여기에 업데이트가 표시됩니다.",
      pt: "As novidades aparecerão aqui quando algo for publicado.",
      "zh-CN": "有内容发布后，更新会显示在这里。",
    }),
    nothingShipped: t({
      en: "Nothing shipped",
      es: "No se publicó nada",
      fr: "Rien de publié",
      ja: "公開なし",
      ko: "출시 없음",
      pt: "Nada publicado",
      "zh-CN": "未发布任何内容",
    }),
    nothingShippedDescription: t({
      en: "This day was intentionally left empty.",
      es: "Este día se dejó vacío intencionadamente.",
      fr: "Cette journée a volontairement été laissée vide.",
      ja: "この日は意図的に空けられています。",
      ko: "이 날은 의도적으로 비워 두었습니다.",
      pt: "Este dia foi deixado vazio intencionalmente.",
      "zh-CN": "这一天是特意留空的。",
    }),
    opensOn: insert(
      t({
        en: "Opens on {{date}}.",
        es: "Se abre el {{date}}.",
        fr: "Ouvre le {{date}}.",
        ja: "{{date}} に公開されます。",
        ko: "{{date}}에 공개됩니다.",
        pt: "Abre em {{date}}.",
        "zh-CN": "将于 {{date}} 开启。",
      })
    ),
    releasesShipped: enu({
      "1": insert(
        t({
          en: "{{count}} release shipped",
          es: "{{count}} lanzamiento publicado",
          fr: "{{count}} version publiée",
          ja: "{{count}} 件のリリースを公開",
          ko: "릴리스 {{count}}건 배포됨",
          pt: "{{count}} lançamento publicado",
          "zh-CN": "已发布 {{count}} 个版本",
        })
      ),
      ">1": insert(
        t({
          en: "{{count}} releases shipped",
          es: "{{count}} lanzamientos publicados",
          fr: "{{count}} versions publiées",
          ja: "{{count}} 件のリリースを公開",
          ko: "릴리스 {{count}}건 배포됨",
          pt: "{{count}} lançamentos publicados",
          "zh-CN": "已发布 {{count}} 个版本",
        })
      ),
    }),
    shippingLog: t({
      en: "Shipping log",
      es: "Registro de publicaciones",
      fr: "Journal des livraisons",
      ja: "リリースログ",
      ko: "출시 로그",
      pt: "Registro de publicações",
      "zh-CN": "发布日志",
    }),
    statusLocked: t({
      en: "Locked",
      es: "Bloqueado",
      fr: "Verrouillé",
      ja: "ロック中",
      ko: "잠김",
      pt: "Bloqueado",
      "zh-CN": "未解锁",
    }),
    statusNoRelease: t({
      en: "No release",
      es: "Sin lanzamiento",
      fr: "Aucune version",
      ja: "リリースなし",
      ko: "릴리스 없음",
      pt: "Sem lançamento",
      "zh-CN": "无发布",
    }),
    statusPending: t({
      en: "Pending",
      es: "Pendiente",
      fr: "En attente",
      ja: "保留中",
      ko: "대기 중",
      pt: "Pendente",
      "zh-CN": "待发布",
    }),
    statusShipped: t({
      en: "Shipped",
      es: "Publicado",
      fr: "Publié",
      ja: "公開済み",
      ko: "배포됨",
      pt: "Publicado",
      "zh-CN": "已发布",
    }),
    statusToday: t({
      en: "Today",
      es: "Hoy",
      fr: "Aujourd'hui",
      ja: "今日",
      ko: "오늘",
      pt: "Hoje",
      "zh-CN": "今天",
    }),
    unitDays: t({
      en: "days",
      es: "días",
      fr: "jours",
      ja: "日",
      ko: "일",
      pt: "dias",
      "zh-CN": "天",
    }),
    unitHours: t({
      en: "hrs",
      es: "h",
      fr: "h",
      ja: "時間",
      ko: "시간",
      pt: "h",
      "zh-CN": "时",
    }),
    unitMinutes: t({
      en: "min",
      es: "min",
      fr: "min",
      ja: "分",
      ko: "분",
      pt: "min",
      "zh-CN": "分",
    }),
    unitSeconds: t({
      en: "sec",
      es: "s",
      fr: "s",
      ja: "秒",
      ko: "초",
      pt: "s",
      "zh-CN": "秒",
    }),
    unlocksAt: insert(
      t({
        en: "Unlocks {{date}} at 00:00 UTC.",
        es: "Se desbloquea el {{date}} a las 00:00 UTC.",
        fr: "Déverrouillage le {{date}} à 00h00 UTC.",
        ja: "{{date}} 00:00 UTC に解除されます。",
        ko: "{{date}} 00:00 UTC에 잠금 해제됩니다.",
        pt: "Desbloqueia em {{date}} às 00:00 UTC.",
        "zh-CN": "将于 {{date}} 00:00 UTC 解锁。",
      })
    ),
    waitingForFirstRelease: t({
      en: "Waiting for the first release...",
      es: "Esperando el primer lanzamiento...",
      fr: "En attente de la première version...",
      ja: "最初のリリースを待っています...",
      ko: "첫 릴리스를 기다리는 중...",
      pt: "Aguardando o primeiro lançamento...",
      "zh-CN": "正在等待首个发布...",
    }),
  },
  key: "launch-week",
} satisfies Dictionary;

export default launchWeekContent;
