import { promises as fs } from "node:fs";
import path from "node:path";

const root = process.cwd();
const examplesDir = path.join(root, "examples");
const indexOutput = path.join(examplesDir, "__index__.tsx");

const toPosixPath = (value: string) => value.split(path.sep).join("/");

const discoverBases = async (): Promise<string[]> => {
  const entries = await fs.readdir(examplesDir, { withFileTypes: true });

  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .toSorted();
};

const listExamples = async (baseName: string): Promise<string[]> => {
  const baseDir = path.join(examplesDir, baseName);

  try {
    const entries = await fs.readdir(baseDir, { withFileTypes: true });

    return entries
      .filter((entry) => entry.isFile() && entry.name.endsWith(".tsx"))
      .map((entry) => entry.name.replace(/\.tsx$/, ""))
      .toSorted();
  } catch (error) {
    if (
      error &&
      typeof error === "object" &&
      "code" in error &&
      error.code === "ENOENT"
    ) {
      return [];
    }

    throw error;
  }
};

const buildIndex = async () => {
  const bases = await discoverBases();
  const records = await Promise.all(
    bases.map(async (baseName) => {
      const names = await listExamples(baseName);
      console.log(`  Found ${names.length} examples for ${baseName}`);
      return [baseName, names] as const;
    })
  );

  let index = `/* eslint-disable typescript-eslint/ban-ts-comment, typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-examples.mts
// Do not edit this file directly.
import * as React from "react"

export const ExamplesIndex: Record<string, Record<string, any>> = {`;

  for (const [baseName, names] of records) {
    if (names.length === 0) {
      continue;
    }

    index += `
  "${baseName}": {`;

    for (const name of names) {
      const importPath = `./${baseName}/${name}`;
      const filePath = toPosixPath(
        path.join("examples", baseName, `${name}.tsx`)
      );

      index += `
    "${name}": {
      component: React.lazy(async () => {
        const mod = await import("${importPath}")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "${name}"
        return { default: mod.default || mod[exportName] }
      }),
      filePath: "${filePath}",
      name: "${name}",
    },`;
    }

    index += `
  },`;
  }

  index += `
}
`;

  await fs.writeFile(indexOutput, `${index.trim()}\n`);
  console.log(`  Generated ${indexOutput}`);
};

await buildIndex();
