import type { Theme } from "@/registry/bases/ink/ui/types";

export const shadesofpurpleTheme: Theme = {
  border: {
    color: "#B362FF",
    focusColor: "#A599E9",
    style: "round",
  },
  colors: {
    accent: "#FF628C",
    accentForeground: "#1E1E3F",
    background: "#2D2B55",
    border: "#B362FF",
    error: "#EC3A37",
    errorForeground: "#1E1E3F",
    focusRing: "#4D21FC",
    foreground: "#A599E9",
    info: "#9EFFFF",
    infoForeground: "#1E1E3F",
    muted: "#1E1E3F",
    mutedForeground: "#B362FF",
    primary: "#FB94FF",
    primaryForeground: "#1E1E3F",
    secondary: "#1E1E3F",
    secondaryForeground: "#A599E9",
    selection: "#4D21FC",
    selectionForeground: "#1E1E3F",
    success: "#3AD900",
    successForeground: "#1E1E3F",
    warning: "#FF9D00",
    warningForeground: "#1E1E3F",
  },
  name: "shadesofpurple",
  spacing: {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    6: 6,
    8: 8,
  },
  typography: {
    base: "",
    bold: true,
    lg: "bold",
    sm: "dim",
    xl: "bold",
  },
};
